# Generated by Django 6.0.1 on 2026-02-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='financial_sophistication_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='intended_consumer_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('profesional', 'Profesional'), ('mixed', 'Mixed')], max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
