# Generated by Django 6.0.1 on 2026-02-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='financial_sophistication_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='intended_consumer_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
