# Generated by Django 6.0.1 on 2026-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_financial_sophistication_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('insurance', 'Insurance'), ('savings', 'Savings'), ('investment', 'Investment'), ('cryptocurrency', 'Cryptocurrency'), ('mortgage', 'Mortgage'), ('cash_isa', 'Cash_isa'), ('Consumer_credit', 'consumer_credit')], max_length=20),
        ),
    ]
