# Generated by Django 6.0.1 on 2026-02-05 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerDutyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_frequency', models.PositiveIntegerField()),
                ('last_consumer_duty_review_date', models.DateTimeField()),
                ('notes_on_known_risks', models.TextField(blank=True, null=True)),
                ('risk_tolerance_assumption', models.CharField(blank=True, choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], max_length=255, null=True)),
                ('vulnerability_consideration', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('mixed', 'Mixed')], max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_duty_reviews', to='product.product')),
            ],
        ),
    ]
