# Generated by Django 6.0.1 on 2026-02-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_consumerdutyreview_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
